name: super_adventure
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: monty <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1